pull_request_rules:
  - name: Check ci status
    conditions:
      - and:
        - check-success=CI/Jenkins/twister
        - or:
          - check-success=CI/Jenkins/integration
          - check-success=CI/Jenkins/integration-skipped
    actions:
      label:
        add:
          - ci-check-success
