queue_rules:
  - name: default
    conditions: []
    allow_inplace_checks: false
pull_request_rules:
  - name: merge using default queue
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - or:
        - label=manifest-homekit
        - label=manifest-find-my
        - label=CI-homekit-test
        - label=CI-find-my-test
      # Disable as brach protection rules will handle this. Keeping for future reference
      #- check-success=CI/Jenkins/twister
      #- or:
        #- check-success=CI/Jenkins/integration
        #- check-neutral=CI/Jenkins/integration
    actions:
      queue:
        name: default
        method: rebase
        update_method: rebase
        update_bot_account: NordicBuilder
        rebase_fallback: none
