pull_request_rules:
  - name: Tesing adding label
    conditions:
      - author=DatGizmo
    actions:
      comment:
        message: "@{{author}} added mergify-test label"
      label:
        add:
          - mergify-test
  - name: Check gh actions
    conditions:
      - check-success=Check OSS history
    actions:
      comment:
        message: Github actions successfull
      label:
        add:
          - mergify-success
