name: Jenkins Trigger
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  workflow_data:
    runs-on: ubuntu-latest
    name: Check action environment
    steps:
      name: print env
        run: |
          printenv
