name: Jenkins Job Trigger

on:
  workflow_run:
    workflows: ["Compliance"]
    types:
      - completed

jobs:
  workflow_data:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success') }}
    name: Send Jenkins Pull Request Webhook
    steps:
      - name: Send Jenkins webhook
        uses: johannes-huther/webhook.sh@v1
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.JENKINS_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.JENKINS_WEBHOOK_SECRET }}
