---

name: Lint yaml files

on:
  pull_request:
    types: [push, opened, reopened, synchronized]
    paths:
      - '.github/test-spec.yml'

jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c  # v3.1.1
        with:
          file_or_dir: .github/test-spec.yml
          config_file: .github/yamllint.yml
