name: Remove CI requested label

on: 
  pull_request_target:

jobs:
  remove_label:
    name: Remove label
    steps:
      - name: removelabel
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          labels: CI-Requested
          type: remove
